name: ajs
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  url_launcher: ^6.3.1
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  supabase: ^2.5.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/imageEvento1.jpg
    - assets/images/imageEvento2.png
    - assets/images/logoNormal.png
    - assets/images/logoRedondaTransparente.png
